# Generated by Django 3.2.6 on 2022-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraperApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
